# Generated by Django 4.2.1 on 2023-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbartex',
            name='end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='navbartex',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
