# Generated by Django 4.2.1 on 2023-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_navbartex_end_time_alter_navbartex_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
