# Generated by Django 4.2.1 on 2023-06-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='navbartex',
            options={'verbose_name': 'Навбартекс', 'verbose_name_plural': 'Навбартексты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
